# Generated by Django 5.0.6 on 2024-05-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
