# Generated by Django 5.0.6 on 2024-05-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0005_team_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamTable',
        ),
    ]
