# Generated by Django 5.0.6 on 2024-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
