# Generated by Django 5.0.6 on 2024-05-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0010_rename_image_team_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='images',
            new_name='image',
        ),
    ]
