# Generated by Django 5.0.6 on 2024-05-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0016_alter_news_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
