# Generated by Django 5.0.6 on 2024-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0017_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
        ),
    ]
