# Generated by Django 5.0.6 on 2024-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0018_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtable',
            name='drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='gd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
