# Generated by Django 5.0.6 on 2024-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
