# Generated by Django 5.0.6 on 2024-05-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_profile_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
    ]
